package cn.anthony.boot.util;

import java.util.Map;
import java.util.TreeMap;

public class Constant {
    public static Map<String, String> frontPageKeyMap = new TreeMap<String, String>() {
	{
	    put("medicalInstitution", "医疗机构");
	    put("organizationCode", "（组织机构代码");
	    put("adminission_no", "病案号");
	    put("patientclass", "医疗付费方式");
	    put("numberOfTimes", "第");
	    put("outpatientnum", "门诊号");
	    put("healthCardNo", "健康卡号");
	    put("pathological", " 病理号");
	    put("name", "姓名");
	    put("sex", "");
	    put("dateOfBirthday", "出生日期");
	    put("age", "年龄");
	    put("country", "国籍");
	    put("birthplace", "出生地");
	    put("nativeplace", "籍贯");
	    put("nationality", "      民族");
	    put("certNo", "身份证号");
	    put("occupation", " 职业");
	    put("marriageStatus", " 婚姻 ");
	    put("homeAddress", "现住址");
	    put("mobilephone", " 电话");
	    put("homePostcode", "邮编");
	    put("registeredaddress", "户口地址");
	    put("registeredemail", "邮编");
	    put("company", "工作单位及地址");
	    put("businessphone", "单位电话");
	    put("businesspostcode", "邮编");
	    put("patientfrom", "病人来源");
	    put("sponsor", "保健人员分类");
	    put("sponsorstatues", "保健人员在岗状态");
	    put("contactName", "联系人姓名");
	    put("relation", "关系");
	    put("contactaddress", "地址");
	    put("contactphone", "电话");
	    put("admissionway", "");
	    put("PresentProvince", " 1.急诊  2.门诊  3.其他医疗机构转入  9.其他  ");
	    put("PresentProvinceCode", "");
	    put("PresentCity", "");
	    put("PresentCityCode", "");
	    put("PresentStreet", "");
	    put("ResidenceProvince", "");
	    put("ResidenceProvinceCode", "");
	    put("ResidenceCity", "");
	    put("ResidenceCityCode", "");
	    put("ResidenceStreet", "  ");
	    put("admissionTime", "入院时间");
	    put("admissionDept", "入院科别");
	    put("admissionWard", "   病房");
	    put("dischargeTime", "出院时间");
	    put("dischargeDept", "出院科别");
	    put("dischargeWard", "   病房");
	    put("inhopitalday", "   实际住院");
	    put("changedept", "转科科别");
	    put("REGISTER_DIAGNOSIS", "门（急）诊诊断　");
	    put("REGISTER_CODE", "疾病编码");
	    put("B0C09B20353444959A675308E7E03FF5", "病情");
	    put("mainDiag", "主要诊断");
	    put("mainDiagCode", "颈内动脉动脉瘤（ICA）(双)");
	    put("admissionCondition", "I72.004");
	    put("E0CE652177A5410183E5A601BF0D5479", "1");
	    put("otherDiag1", "其他诊断");
	    put("otherDiagCode1", "颈内动脉动脉瘤栓塞术后");
	    put("admissionCondition1", "          ");
	    put("3A077F2D3157424595099E81A6B3A9F7", "病情");
	    put("otherDiag11", "其他诊断");
	    put("1F3B818798AF4387A6FFE357C269477C", "          ");
	    put("11E0B12464DE4628A2989A12A2A0732C", "          ");
	    put("EXTERNAL_CAUESES", "损伤、中毒的外部原因");
	    put("EXTERNAL_CODE", "疾病编码");
	    put("PATHOLOGY_DIAGNOSIS", "病理诊断");
	    put("PATHOLOGY_CODE", "疾病编码");
	    put("drugAllergy", "");
	    put("ALLERGIC_DRUG", " 1.无 2.有，过敏药物");
	    put("deadAutopsy", "");
	    put("ABO", "");
	    put("Rh", "");
	    put("redBloodCell", "红细胞");
	    put("platelet", "血小板");
	    put("plasma", "血浆");
	    put("wholeBlood", "全血");
	    put("other", "其它");
	    put("KZR_DOCTOR_NAME", "科 主 任");
	    put("ZRFZR_DOCTOR_NAME", "主任（副主任）医师");
	    put("ZZ_DOCTOR_NAME", "主治医师");
	    put("ZY_DOCTOR_NAME", "住院医师");
	    put("ZZHEN_DOCTOR_NAME", "主诊医师");
	    put("ZR_NURSE_NAME", "责任护士");
	    put("JX_DOCTOR_NAME", "进修医师");
	    put("SX_DOCTOR_NAME", "实习医师");
	    put("coder", "编 码 员");
	    put("ZK_DJ1", "");
	    put("ZK_DOCTOR_NAME", "质控医师");
	    put("qualityControlDate", "质控日期");
	    put("ZK_NURSE_NAME", "质控护士");
	    put("imagSignature1", "填报医师");
	    put("TB_DOC_CODE", "");
	    put("TB_DOC_NAME", "0210508");
	    put("beforeday", " 入院前");
	    put("beforehours", "天");
	    put("beforeminutes", "小时");
	    put("afterday", "分钟    入院后");
	    put("afterhours", "天");
	    put("afterminutes", "小时");
	    put("SEVERENAME1", "出重症监护室时间");
	    put("SEVERECODE1", " - ");
	    put("INSEVERETIME1", " - ");
	    put("OUTSEVERETIME1", " - ");
	    put("SEVERENAME2", " - ");
	    put("SEVERECODE2", " - ");
	    put("INSEVERETIME2", " - ");
	    put("OUTSEVERETIME2", " - ");
	    put("SEVERENAME3", " - ");
	    put("SEVERECODE3", " - ");
	    put("INSEVERETIME3", " - ");
	    put("OUTSEVERETIME3", " - ");
	    put("SEVERENAME4", " - ");
	    put("SEVERECODE4", " - ");
	    put("INSEVERETIME4", " - ");
	    put("OUTSEVERETIME4", " - ");
	    put("SEVERENAME5", " - ");
	    put("SEVERECODE5", " - ");
	    put("INSEVERETIME5", " - ");
	    put("OUTSEVERETIME5", " - ");
	    put("respirator", "呼吸机使用时间");
	    put("ZLFQ", "");
	    put("T", "  T");
	    put("N", " N");
	    put("M", " M");
	    put("FQ", "；");
	    put("BX", "0期 Ⅰ期 Ⅱ期 Ⅲ期 Ⅳ期；");
	    put("incli", "");
	    put("clivar", "");
	    put("quitcli", "");
	    put("inhosgrade", "入院");
	    put("outhosgrade", "出院");
	    put("birthWeight", "新生儿出生体重");
	    put("admissionWeight", "新生儿入院体重");
	    put("hospitalizationPlanAgain", "");
	    put("purpose", " 1.无  2.有，目的");
	    put("outclass", "");
	    put("outToHospital", " 1.医嘱离院  2.医嘱转院，拟接收医疗机构名称");
	    put("outToCommunity", "3.医嘱转社区卫生服务机构/乡镇卫生院，拟接收医疗机构名称");
	}
    };
    public static Map<String, String> inKeyMap = new TreeMap<String, String>() {
	{
	    put("takingFrom", "病史叙述人");
	    put("reliability", "可靠性");
	    put("contact", "亲属姓名、电话");
	    put("selfDesc", "自述病史");
	    put("nowMedicalHistory", "现病史");
	    put("pastMedicalHistory", "既往史");
	    put("infectiousHistory", "传染史");
	    put("lifeHistory", "个人生活史");
	    put("familyHistory", "家族史");
	    put("general", "一般情况");
	    put("T", "体温");
	    put("P", "心率");
	    put("R", "R");
	    put("BP", "血压");
	    put("skin", "皮肤粘膜");
	    put("superficialLymph", "浅表淋巴结");
	    put("skull", "头颅");
	    put("eye", "眼");
	    put("ear", "耳");
	    put("node", "鼻");
	    put("mouse", "口腔");
	    put("throat", "咽");
	    put("neck", "颈    部");
	    put("thorax", "胸廓");
	    put("lung", "肺");
	    put("heart", "心");
	    put("bloodVessels", "周围血管征");
	    put("abdomen", "腹    部");
	    put("liver", "肝（胆）");
	    put("spleen", "脾");
	    put("kidney", "肾");
	    put("vulva", "外阴及肛门");
	    put("spine", "脊    柱");
	    put("limbs", "四肢（关节）");
	    put("nervousSystem", "神经系统");
	    put("sExamination", "专科情况");
	    put("firstDiag", "初步诊断");
	    put("confirmDiag", "确定诊断");
	    put("correctDiag", "更正诊断");
	    put("supplyDiags", "补充诊断");
	}
    };
    public static Map<String, String> operKeyMap = new TreeMap<String, String>() {
	{
	    put("operationDpt", "科别");
	    put("bedNumber", "床位号");
	    put("preDiagnosis", "术前诊断");
	    put("operataionDiagnosis", "术中诊断");
	    put("operationTitle", "手术名称");
	    put("doctor", "手术医师");
	    put("assistant", "助手");
	    put("beginTime", "开始时间");
	    put("endTime", "结束时间");
	    put("anaesthetic", "麻醉方法");
	    put("bloodLoss", "失血量");
	    put("bloodTransfusion", "输血量");
	    put("detail", "手术经过");
	}
    };
    public static Map<String, String> outKeyMap = new TreeMap<String, String>() {
	{
	    put("department", "科别");
	    put("outDate", "出院时间");
	    put("inDescriotion", "入院时情况");
	    put("inDiagnosis", "入院诊断");
	    put("treatment", "入院后诊疗经过");
	    put("outDescription", "出院时情况");
	    put("outDiagnosis", "出院诊断");
	    put("operationDesc", "手术名称及伤口愈合情况");
	    put("dischargeOrder", "出院医嘱");
	}
    };
}
